version: '3.8'

services:
  frontend:
    image: todo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: frontend
